### ISSUE TITLE
Lost my authenticator

### ISSUE THREAD

**Issue by Toaster496** [jerfer1111/EnableWindowsHelloOnManagedaDevices#1]
as the title says I have lost my authenticator account how do I get it back?
thanks jerms

**Comment by jerfer1111** [comment]
Hi Toaster496,
As stated earlier, it is recommended to set up with Microsoft Authenticator. To fix this issue, you will need to request to remove the authentication method by your Organisation or Administrator of your domain.

Kind Regards,
Jeremiah
